### ISSUE TITLE
テストをするためのモジュール等が足りない

### ISSUE THREAD

**Issue by kebus426** [rclex/rclex#14]
テストのために作ったノードの情報を取得、解析等ができるようなテスト用のモジュールが必要。
例えばRclexでノードを作成した際、意図した通りに作られているかどうかを確認するために作成したノードの情報がリストに変換されれば自分が意図していたノードの情報をリストに書いて比較することできちんと作成できていたかどうか判別できる。
また、subscriberのcallback関数はmsgのみを引数に取るのでテストの親プロセスの情報を渡せず、プロセス間でデータのやり取りが出来ない（現在は一時ファイルを作成し、そこで読み書きを行うことでデータのやり取りを行っている）。これらをどうにか受け渡す方法が必要。

**Comment by takasehideki** [comment]
`pub_callback/1` `sub_callback/1` での処理のために任意の引数を渡すとか，個数も任意にするためにタプルで渡すとか，にしたら良いかも．

**Comment by kebus426** [comment]
ある程度実装したのでcloseします。
