### ISSUE TITLE
Improve Makefile to compile with galactic and humble

### ISSUE THREAD

**Issue by pojiro** [rclex/rclex#154]
Current Makefile supports dashing and foxy only,

https://github.com/rclex/rclex/blob/64533cb3193f579ce60cd2ce9f105980de46e27e/Makefile#L4-L10

so we cannot test galactic and humble with docker, like below

```
$ export RCLEX_DOCKER_TAG=galactic-ex1.13.1-otp24.1.7
$ docker compose run --rm -w /root/rclex rclex_docker mix test
gcc -c -I/usr/local/lib/erlang/usr/include -I/opt/ros/galactic/include -I/opt/ros/galactic/include -I/opt/ros/galactic/include -g -O2 -Wall -Wextra -Wno-unused-parameter -pedantic -fPIC -I./src -D2 -o /root/rclex/_build/test/lib/rclex/obj/msg_nif.o src/msg_nif.c
<command-line>: error: macro names must be identifiers
make: *** [Makefile:75: /root/rclex/_build/test/lib/rclex/obj/msg_nif.o] Error 1
** (Mix) Could not compile with "make" (exit status: 2).
If the error message above says that rcl/rcl.h can't be found,
then the fix is to setup the ROS 2 environment. If you have
already installed ROS 2 environment, run the following command.
`. /opt/ros/${ROS_DISTRO}/setup.bash`
```

This caused by `<command-line>: error: macro names must be identifiers`, which means `-D2` isn't valid.
That must be '-DGALACTIC' in this case.

**Comment by takasehideki** [comment]
We have stopped the support for Dashing at https://github.com/rclex/rclex/pull/189, so Distribution-based branching by macro was no longer required in the source code.
We can close this!
