### ISSUE TITLE
Enrich `mix test`

### ISSUE THREAD

**Issue by takasehideki** [rclex/rclex#95]
Current `mix test` only targets on only basic functions. We need to support the behavior of all APIs as much as possible.

**Comment by takasehideki** [comment]
#113 has satisfied part of this issue. I think the remaining is to verify the creation and communication of the topic using a custom message type such as Twist.

**Comment by s-hosoai** [comment]
I know. Tests are not rich yet. However, refactoring affect the test code. I will add tests with refactoring.

**Comment by takasehideki** [comment]
We close this issue with big thanks to the awesome contributions by @pojiro (e.g., #136)
